=== Breina/MC-ticker/conf/tilemaps.xsd
<xs:schema attributeFormDefault="unqualified"
	elementFormDefault="qualified"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="tileset">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="entry" type="nodeType" maxOccurs="unbounded" minOccurs="0" />
			</xs:sequence>
			<xs:attribute type="xs:string" name="name"/>
			<xs:attribute type="xs:string" name="extension"/>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="nodeType">
		<xs:sequence>
			<xs:element type="xs:string" name="name" minOccurs="0" maxOccurs="1"/>
			<xs:element name="condition" type="conditionType" maxOccurs="unbounded" minOccurs="0" />
			<xs:element name="top" type="nodeType" maxOccurs="1" minOccurs="0"/>
			<xs:element name="front" type="nodeType" maxOccurs="1" minOccurs="0"/>
			<xs:element name="right" type="nodeType" maxOccurs="1" minOccurs="0"/>
		</xs:sequence>
		
		<xs:attribute type="xs:short" name="rotation" use="optional"/>
		<xs:attribute type="xs:string" name="mirror" use="optional"/>
	</xs:complexType>
	
	<xs:complexType name="conditionType">
		<xs:sequence>
			<xs:element type="xs:string" name="name" minOccurs="0" maxOccurs="1"/>
			<xs:element name="condition" type="conditionType" maxOccurs="unbounded" minOccurs="0" />
			<xs:element name="top" type="nodeType" maxOccurs="1" minOccurs="0"/>
			<xs:element name="front" type="nodeType" maxOccurs="1" minOccurs="0"/>
			<xs:element name="right" type="nodeType" maxOccurs="1" minOccurs="0"/>
		</xs:sequence>
		
		<xs:attribute type="xs:short" name="id" use="optional"/>
		<xs:attribute type="xs:byte" name="data" use="optional"/>
		<xs:attribute type="xs:byte" name="mask" use="optional"/>
		
		<xs:attribute type="xs:short" name="rotation" use="optional"/>
		<xs:attribute type="xs:string" name="mirror" use="optional"/>
	</xs:complexType>
</xs:schema>

=== Breina/MC-ticker/conf/tilemaps.xml
<?xml version='1.1' encoding='UTF-8'?>
<tileset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="./tilemaps.xsd" 
	name="default" extension="png">

	<entry>
		<condition id="20">
			<name>glass</name>
		</condition>
		
		<condition id="95">
			<name>glass</name>
		</condition>
	</entry>
	
	<entry>
		<condition id="165">
			<name>slimeblock</name>
		</condition>
	</entry>
	
	<entry>
		<condition id="107">
			<name>fencegate</name>
		</condition>
		
		<condition data="0" mask="4">
			<name>closed</name>
		</condition>
		
		<condition data="4" mask="4">
			<name>open</name>
		</condition>
		
		<top>
			<name>top</name>
			
			<condition data="0" mask="3" rotation="180" />
			<condition data="1" mask="3" rotation="270" />
			<condition data="3" mask="3" rotation="90" />
		</top>
		
		<front>
			<condition data="0" mask="3">
				<name>front</name>
			</condition>
			
			<condition data="1" mask="3" mirror="horizontal">
				<name>side</name>
			</condition>
			
			<condition data="2" mask="3">
				<name>front</name>
			</condition>
			
			<condition data="3" mask="3">
				<name>side</name>
			</condition>
		</front>
		
		<right>
			<condition data="0" mask="3" mirror="horizontal">
				<name>side</name>
			</condition>
			
			<condition data="1" mask="3">
				<name>front</name>
			</condition>
			
			<condition data="2" mask="3">
				<name>side</name>
			</condition>
			
			<condition data="3" mask="3">
				<name>front</name>
			</condition>
		</right>
	</entry>
	
	<entry>
		<condition id="138">
			<name>beacon</name>
		</condition>
		
		<top>
			<name>top</name>
		</top>
		
		<front>
			<name>side</name>
		</front>
		
		<right>
			<name>side</name>
		</right>	
	</entry>
	
	<entry>
		<condition id="79">
			<name>ice</name>
		</condition>
	</entry>
	
	<entry>
		<condition id="152">
			<name>redstoneblock</name>
		</condition>
	</entry>
	
	<entry>
		<condition id="174">
			<name>packedice</name>
		</condition>
	</entry>
	
	<entry>		
		<condition id="44">
			<name>slab</name>
		</condition>
		
		<condition id="126">
			<name>slab</name>
		</condition>
		
		<top>
			<name>top</name>
		</top>
		
		<front>
			<condition data="0" mask="8">
				<name>side-bottom</name>
			</condition>
			
			<condition data="8" mask="8">
				<name>side-top</name>
			</condition>			
		</front>
		
		<right>
			<condition data="0" mask="8">
				<name>side-bottom</name>
			</condition>
			
			<condition data="8" mask="8">
				<name>side-top</name>
			</condition>			
		</right>
	</entry>
	
	<entry>
		<condition id="51">
			<name>fire</name>
		</condition>
	</entry>
	
	<entry>
		<condition id="69">
			<name>lever</name>
		</condition>
		
		<top>
			<condition data="0" mask="8">
				<name>off</name>
			
				<condition data="0" mask="7" rotation="270">
					<name>top-back</name>
				</condition>
				
				<condition data="1" mask="7" rotation="90">
					<name>front</name>
				</condition>
				
				<condition data="2" mask="7" rotation="270">
					<name>front</name>
				</condition>
				
				<condition data="3" mask="7" rotation="180">
					<name>front</name>
				</condition>
				
				<condition data="4" mask="7">
					<name>front</name>
				</condition>
				
				<condition data="5" mask="7">
					<name>top-front</name>
				</condition>
				
				<condition data="6" mask="7" rotation="270">
					<name>top-front</name>
				</condition>
				
				<condition data="7" mask="7" rotation="180">
					<name>top-back</name>
				</condition>
			</condition>
		
			<condition data="8" mask="8">
				<name>on</name>
			
				<condition data="0" mask="7" rotation="90">
					<name>top-back</name>
				</condition>
				
				<condition data="1" mask="7" rotation="90">
					<name>back</name>
				</condition>
				
				<condition data="2" mask="7" rotation="270">
					<name>back</name>
				</condition>
				
				<condition data="3" mask="7" rotation="180">
					<name>back</name>
				</condition>
				
				<condition data="4" mask="7">
					<name>back</name>
				</condition>
				
				<condition data="5" mask="7" rotation="180">
					<name>top-front</name>
				</condition>
				
				<condition data="6" mask="7" rotation="90">
					<name>top-front</name>
				</condition>
				
				<condition data="7" mask="7">
					<name>top-back</name>
				</condition>
			</condition>
		</top>
		
		<front>
			<condition data="0" mask="8">
				<name>off</name>
				
				<condition data="0" mask="7" mirror="vertical">
					<name>side</name>
				</condition>
				
				<condition data="1" mask="7" rotation="90" mirror="vertical">
					<name>side</name>
				</condition>
				
				<condition data="2" mask="7" rotation="270">
					<name>side</name>
				</condition>
				
				<condition data="3" mask="7" rotation="180">
					<name>top-front</name>
				</condition>
				
				<condition data="4" mask="7" rotation="180">
					<name>top-back</name>
				</condition>
				
				<condition data="5" mask="7">
					<name>front</name>
				</condition>
				
				<condition data="6" mask="7">
					<name>side</name>
				</condition>
				
				<condition data="7" mask="7" rotation="180">
					<name>front</name>
				</condition>
			</condition>
			
			<condition data="8" mask="8">
				<name>on</name>
				
				<condition data="0" mask="7" rotation="180">
					<name>side</name>
				</condition>
				
				<condition data="1" mask="7" rotation="90">
					<name>side</name>
				</condition>
				
				<condition data="2" mask="7" rotation="270" mirror="vertical">
					<name>side</name>
				</condition>
				
				<condition data="3" mask="7">
					<name>top-front</name>
				</condition>
				
				<condition data="4" mask="7">
					<name>top-back</name>
				</condition>
				
				<condition data="5" mask="7">
					<name>back</name>
				</condition>
				
				<condition data="6" mask="7" mirror="horizontal">
					<name>side</name>
				</condition>
				
				<condition data="7" mask="7" rotation="180">
					<name>back</name>
				</condition>
			</condition>
		</front>
		
		<right>
			<condition data="0" mask="8">
				<name>off</name>
				
				<condition data="0" mask="7" rotation="180">
					<name>front</name>
				</condition>
				
				<condition data="1" mask="7" rotation="180">
					<name>top-front</name>
				</condition>
				
				<condition data="2" mask="7" rotation="180">
					<name>top-back</name>
				</condition>
				
				<condition data="3" mask="7" rotation="270">
					<name>side</name>
				</condition>
				
				<condition data="4" mask="7" rotation="90" mirror="vertical">
					<name>side</name>
				</condition>
				
				<condition data="5" mask="7" mirror="horizontal">
					<name>side</name>
				</condition>
				
				<condition data="6" mask="7">
					<name>front</name>
				</condition>
				
				<condition data="7" mask="7" rotation="180">
					<name>side</name>
				</condition>
			</condition>
			
			<condition data="8" mask="8">
				<name>on</name>
				
				<condition data="0" mask="7" rotation="180">
					<name>back</name>
				</condition>
				
				<condition data="1" mask="7">					
					<name>top-front</name>
				</condition>
				
				<condition data="2" mask="7">
					<name>top-back</name>
				</condition>
				
				<condition data="3" mask="7" rotation="270" mirror="vertical">
					<name>side</name>
				</condition>
				
				<condition data="4" mask="7" rotation="90">
					<name>side</name>
				</condition>
				
				<condition data="5" mask="7">
					<name>side</name>
				</condition>
				
				<condition data="6" mask="7">
					<name>back</name>
				</condition>
				
				<condition data="7" mask="7" rotation="180" mirror="horizontal">
					<name>side</name>
				</condition>
			</condition>
		</right>
	</entry>
	
	<entry>
		<condition id="89">
			<name>glowstone</name>
		</condition>
	</entry>

	<entry>
		<name>rail</name>
		
		<condition id="66">
			<condition data="6">
				<name>bent</name>
				
				<top>
					<name>top</name>
				</top>
				
				<front>
					<name>side-back</name>
				</front>
				
				<right mirror="horizontal">
					<name>side-back</name>
				</right>
			</condition>
			
			<condition data="7">
				<name>bent</name>
				
				<top rotation="90">
					<name>top</name>
				</top>
				
				<front mirror="horizontal">
					<name>side-back</name>
				</front>
				
				<right mirror="horizontal">
					<name>side-front</name>
				</right>
			</condition>
			
			<condition data="8">
				<name>bent</name>
				
				<top rotation="180">
					<name>top</name>
				</top>
				
				<front mirror="horizontal">
					<name>side-front</name>
				</front>
				
				<right>
					<name>side-front</name>
				</right>
			</condition>
			
			<condition data="9">
				<name>bent</name>
				
				<top rotation="270">
					<name>top</name>
				</top>
				
				<front>
					<name>side-front</name>
				</front>
				
				<right>
					<name>side-back</name>
				</right>
			</condition>
		</condition>
		
		<condition id="27">
			<name>powered</name>
			
			<condition data="0" mask="8">
				<name>off</name>
			</condition>
			
			<condition data="8" mask="8">
				<name>on</name>
			</condition>
		</condition>
		
		<condition id="28">
			<name>detector</name>
			
			<condition data="0" mask="8">
				<name>off</name>
			</condition>
			
			<condition data="8" mask="8">
				<name>on</name>
			</condition>
		</condition>
		
		<condition id="157">
			<name>activator</name>
			
			<condition data="0" mask="8">
				<name>off</name>
			</condition>
			
			<condition data="8" mask="8">
				<name>on</name>
			</condition>
		</condition>
		
		<condition data="0" mask="7">
			<top>
				<name>top</name>
			</top>
			
			<front>
				<name>side-flat-straight</name>
			</front>
			
			<right>
				<name>side-flat-cross</name>
			</right>
		</condition>
		
		<condition data="1" mask="7">
			<top rotation="90">
				<name>top</name>
			</top>
			
			<front>
				<name>side-flat-cross</name>
			</front>
			
			<right>
				<name>side-flat-straight</name>
			</right>
		</condition>
		
		<condition data="2" mask="7">
